name: Website building

# When pushing on master
on:
  push:
    branches:
      - master

jobs:
  deploy_pages:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      # Checkout, configure boilerplate
      # cf https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      # Building
      - name: Install dependencies
        run: sudo apt-get install php-cli php-curl php-mbstring php-xml composer
      - name: Composer install
        run: composer install
      
      - name: Generate site
        run: make

      # Deploying to GitHub pages
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: web/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4